[project]
name = "graph-tunnel"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.network-participants]
path = "contracts/network-participants.clar"
depends_on = []

[contracts.network-graph]
path = "contracts/network-graph.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
